### ISSUE TITLE
Widget Categorization in Management Area

### ISSUE THREAD

**Issue by eazuka** [impresspages/ImpressPages#311]
With the on going re-factoring of ImpressPages and Plans to introduce Plugin Market, there is need to introduce widget Categorization in Management Area. At the moment, widgets are all listed in the widget bar without categorization, and one has to scroll left or right to get to the desired widget. In a situation where there are lots of widgets installed, it becomes very stressful to scroll left/right.

Also, not having widget categorization is kind of limiting some creative ideas, because some plugins ideas requires the creation of multiple widgets that wouldn't be ideal to list all as it is at the moment.

Therefore i hope the team can look into adding the widget categorization in admin/management area.

**Comment by HalcyonD** [comment]
I have a 'prototype' of a possible way to implement this though it would need a jQuery Tools Scrollable library replacement, because it easily breaks and is very limited (currently I have my custom implementation, but there are some issues with it and it doesn't include scrollable tabs):

http://youtu.be/txATycMsSLw

The only problem I see is it can cause tabs galore if there aren't any pre-defined categories (+ already translated ones), you know, someone will write singular names, other - plural, etc..

**Comment by maskas** [comment]
Nice start. 

Regarding different group names, I made a decision some time ago to group widgets by plugin name not by what they do. And only if you, as a user, don't like that, you can do some shufling on your instalation. But by default all widgets of a single plugin are under a single tab. That also means that widget developers don't need to worry about group name at all. Tabs like "All plugins" and "Favorite" would solve 99% of the problems I think.

Additional space taken by the tabs is something we would like to avoid. I would better go with solution like this:

![image](https://cloud.githubusercontent.com/assets/1159983/5794384/505f31c6-9f73-11e4-9623-2d4b3fdf64d1.png)

For a long time we are planning to move widgets to the left side and group as an accordion. That would be the best, I think.

**Comment by eazuka** [comment]
@HalcyonD really nice work.
@maskas if you mean moving widget to the left size of page as oppose to the top of page as it is at moment, i think it's a bad decision from my view. The widget at the Top of page as it is at the moment doesn't disturb normal site design. as you can see your normal page design and size without something at the left or right disrupting.

**Comment by maskas** [comment]
On wide screens this is very highly requested feature. I don't see any issues having both layouts. So that user coud choose the one he likes the best. I would use widgets on a side as I have tons of free space on the left.

**Comment by eazuka** [comment]
if ther is the option of choice, then i agree with you as users can use which they prefer but if it's just one choice of top or left, I think being at the top makes more sense.

**Comment by HalcyonD** [comment]
I doubt there is a customizable "Settings" page o/. If grouping by plugin name, wouldn't it mean that when you have 10 plugins with widgets, you'll have 10 (+ core, favorites) tabs? I don't really see/know an elegant way to have that many at the top and keep it responsive without tabs. Having it on the side would prove the same issue about responsive design? or it's not something important? Also, having favorites would mean having to deal with multiple users /o\

**Comment by maskas** [comment]
Regarding the count of groups. Maybe the algorithm could be smart? What if we put a separate tab for plugins that introduce more than two widgets? And other plugins that introduce only one additional widget goes to "other" group? Then, I guess, 99% of the time you would have following groups:
Core, User, Other

Let's forget about favorites for now. It just distracts us from the core problem.

Regarding side / top for sure we need an option because there will be situation when side way of doing won't work because of unique design.

I would go for top version as shown on image + side version.

![image](https://cloud.githubusercontent.com/assets/1159983/5798861/7bb1bb08-9fd4-11e4-9ad1-841418f0b6ec.png)

**Comment by jankus** [comment]
What happens when we have 7 or more tabs?

**Comment by maskas** [comment]
New column appears. We can have as much as we like. We may also have just three listed by default and other groups appear as a dropdown. There are many ways to list those groups without taking additional line of screen.

**Comment by jankus** [comment]
Yes, we should treat the height as gold. We have way more space horizontally. Of course, mobile screens are another story.

**Comment by maskas** [comment]
on mobile probably you don't have categorization.

**Comment by HalcyonD** [comment]
I almost have it done, it'll show categories based on plugin names and only:

1. If there are plugins with widgets
2. Desktop only

Otherwise it'll show a single list as it is now. The only bug right now is the scrolling :\ not sure if you'd implement a custom library (because the present one - jquery tools scrollable - didn't fit in nicely) or I need to complete my custom one which at the moment miscalculates the right offset for the list and doesn't allow to scroll if the last item is less than half covered.

![untitled](https://cloud.githubusercontent.com/assets/8076512/5808637/68c68514-a038-11e4-9fb3-0cb3cd864deb.png)

**Comment by jankus** [comment]
jQuery Tools was pretty cool library, once. Now it's dead and we definitely need to find an alternative to it. It has drawbacks but covers key requirements how things should work. If someone has an alternative for it, just let me know and I'll investigate.

Features that we require:
- quick recalculation when filtering
- recalculate on screen resize
- touch support
- both horizontal and vertical scrolling
- scroll by pages
- stick to avaiable HTML and not adding it's own on the fly

**Comment by maskas** [comment]
I doubt we need a vertical scrolling. Left side should done using accordion and regular browser scroll I guess.

**Comment by HalcyonD** [comment]
For similar functionality I always used OwlCarousel but it does add it's own structure when you init it.

**Comment by maskas** [comment]
Maybe that structure won't be harmful? I probably don't mind.

**Comment by jankus** [comment]
It will, since it adds it's own classes. It means it will collide with all themes which use it.

**Comment by maskas** [comment]
Good point. I believe we can have a prefixed version with prefixed classes to get around this.

**Comment by HalcyonD** [comment]
Can always modify the js to IP needs. The library contains the options to change main container class, so maybe even modify it to include a wider customization and provide as a default carousel option for themes. Not sure though about OwlCarousel 2 beta as the dev stopped updating it.

**Comment by HalcyonD** [comment]
OwlCarousel works no problem, but it suffers from the same issue as every other - it tries to make the items fill the entire space and you have to specify how many items you want it to show. It's possible to make the `scrollable` compatble with some tweaking :\

**Comment by HalcyonD** [comment]
I finally sat down to make a branch for [widget categorization](https://github.com/HalcyonD/ImpressPages/tree/widget-categories). Made a slight adjustment to the 'scrollable' script to make it work. I hope I didn't forget anything.

**Comment by maskas** [comment]
Looks like an awesome work!

**Comment by maskas** [comment]
Are you going to issue a pull request or should I just take the code from your repository?

**Comment by HalcyonD** [comment]
I was hoping to get someone else have a look to make sure everything works as expected before making a request. It's hard to notice your own bugs :D

**Comment by maskas** [comment]
It has been released already.
